pr: none
trigger:
  - master

jobs:
- job: 'Build'
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    gh_name: $(gh_username)
    gh_email: $(gh_useremail)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7.x'
  - script: |
      echo %BUILD_REPOSITORY_URI%
      git config user.email %gh_email%
      git config user.name %gh_name%
      git config --global http.%BUILD_REPOSITORY_URI%/.extraHeader "Authorization: Basic %gh_pat%"
    env:
      gh_pat: $(gh_userpat)
  - script: |
      pip install mkdocs
      mkdocs --version
      mkdocs gh-deploy
